### ISSUE TITLE
UnsupportedOperationException in AndroidModel

### ISSUE THREAD

**Issue by bnord01** [mohrm/android-analyzer#1]
Running quickscan with call graph construction on nu.firetech.android.wifiwarning_6.apk from fdroid yields the following exception:

```
Exception in thread "main" java.lang.UnsupportedOperationException: Can not handle the callers android-context of <Primordial,Landroid/view/ContextThemeWrapper>
        at com.ibm.wala.dalvik.ipa.callgraph.androidModel.stubs.AndroidStartComponentTool.fetchCallerContext(AndroidStartComponentTool.java:311)
        at com.ibm.wala.dalvik.ipa.callgraph.androidModel.AndroidModel.getMethodAs(AndroidModel.java:706)
        at com.ibm.wala.dalvik.ipa.callgraph.propagation.cfa.IntentContextInterpreter.getIR(IntentContextInterpreter.java:224)
        at com.ibm.wala.ipa.callgraph.propagation.cfa.DelegatingSSAContextInterpreter.getIR(DelegatingSSAContextInterpreter.java:51)
        at com.ibm.wala.ipa.callgraph.propagation.cfa.DelegatingSSAContextInterpreter.getIR(DelegatingSSAContextInterpreter.java:51)
        at com.ibm.wala.ipa.callgraph.impl.ExplicitCallGraph$ExplicitNode.getIR(ExplicitCallGraph.java:309)
        at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder.getTargetPointerKey(SSAPropagationCallGraphBuilder.java:2076)
        at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder.processCallingConstraints(SSAPropagationCallGraphBuilder.java:1531)
        at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder.processResolvedCall(SSAPropagationCallGraphBuilder.java:1485)
        at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder.access$100(SSAPropagationCallGraphBuilder.java:96)
        at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder$DispatchOperator.handleAllReceivers(SSAPropagationCallGraphBuilder.java:1762)
        at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder$DispatchOperator.evaluate(SSAPropagationCallGraphBuilder.java:1684)
        at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder$DispatchOperator.evaluate(SSAPropagationCallGraphBuilder.java:1574)
        at com.ibm.wala.fixedpoint.impl.GeneralStatement.evaluate(GeneralStatement.java:37)
        at com.ibm.wala.fixedpoint.impl.AbstractFixedPointSolver.incorporateNewStatement(AbstractFixedPointSolver.java:290)
        at com.ibm.wala.fixedpoint.impl.AbstractFixedPointSolver.newStatement(AbstractFixedPointSolver.java:436)
        at com.ibm.wala.ipa.callgraph.propagation.PropagationSystem.newSideEffect(PropagationSystem.java:589)
        at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder$ConstraintVisitor.visitInvokeInternal(SSAPropagationCallGraphBuilder.java:1095)
        at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder$ConstraintVisitor.visitInvoke(SSAPropagationCallGraphBuilder.java:1030)
        at com.ibm.wala.ssa.SSAInvokeInstruction.visit(SSAInvokeInstruction.java:87)
        at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder.addBlockInstructionConstraints(SSAPropagationCallGraphBuilder.java:277)
        at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder.addNodeInstructionConstraints(SSAPropagationCallGraphBuilder.java:256)
        at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder.unconditionallyAddConstraintsFromNode(SSAPropagationCallGraphBuilder.java:229)
        at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder.addConstraintsFromNode(SSAPropagationCallGraphBuilder.java:195)
        at com.ibm.wala.ipa.callgraph.propagation.PropagationCallGraphBuilder.addConstraintsFromNewNodes(PropagationCallGraphBuilder.java:340)
        at com.ibm.wala.ipa.callgraph.propagation.StandardSolver.solve(StandardSolver.java:58)
        at com.ibm.wala.ipa.callgraph.propagation.PropagationCallGraphBuilder.makeCallGraph(PropagationCallGraphBuilder.java:273)
        at edu.kit.joana.wala.core.SDGBuilder.buildCallgraph(SDGBuilder.java:1028)
        at edu.kit.joana.wala.core.SDGBuilder.run(SDGBuilder.java:531)
        at edu.kit.joana.wala.core.SDGBuilder.build(SDGBuilder.java:414)
        at edu.kit.joana.wala.core.SDGBuilder.build(SDGBuilder.java:459)
        at edu.kit.jodroid.AndroidAnalysis.justScan(Unknown Source)
        at edu.kit.jodroid.QuickScanner.main(Unknown Source)
```

**Comment by bnord01** [comment]
Same error on de.antonwolf.agendawidget_22.apk from fdroid.

**Comment by bnord01** [comment]
Same error on 
com.dngames.mobilewebcam_90.apk 
com.alexkang.x3matrixcalculator_6.apk

**Comment by mohrm** [comment]
The only purpose of AndroidStartComponentTool.fetchCallerContext seems to be grabbing additional debug information - so this is a stupid way to cause crashes...
