### ISSUE TITLE
NoSuchElementException in CallGraph.<init>

### ISSUE THREAD

**Issue by bnord01** [mohrm/android-analyzer#10]
Running quickcheck (with call graph construction) on 

com.anysoftkeyboard.theme.classic_pc_2.apk
com.hexad.bluezime.hidenabler_1.apk

yields the following error:

```
Exception in thread "main" java.util.NoSuchElementException
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1431)
        at java.util.HashMap$KeyIterator.next(HashMap.java:1453)
        at edu.kit.joana.wala.core.CallGraph.<init>(CallGraph.java:138)
        at edu.kit.joana.wala.core.CallGraph.build(CallGraph.java:39)
        at edu.kit.joana.wala.core.SDGBuilder.convertAndPruneCallGraph(SDGBuilder.java:1047)
        at edu.kit.joana.wala.core.SDGBuilder.run(SDGBuilder.java:554)
        at edu.kit.joana.wala.core.SDGBuilder.run(SDGBuilder.java:537)
        at edu.kit.joana.wala.core.SDGBuilder.build(SDGBuilder.java:414)
        at edu.kit.joana.wala.core.SDGBuilder.build(SDGBuilder.java:459)
        at edu.kit.jodroid.AndroidAnalysis.justScan(Unknown Source)
        at edu.kit.jodroid.QuickScanner.main(Unknown Source)
```

**Comment by mohrm** [comment]
This happens if Joana's standard call graph pruning is enabled and the Android magic does not find any application entry points. Then, the call graph entirely consists of synthetic and primordial methods which all get pruned away, resulting in an empty call graph.
Looking at this particular app, I suspect that there is a bug in the Android magic...but the call graph pruning also does not seem to work well with the Android stuff because the Android stuff produces a call graph with a synthetic root and it does not seem right that this gets pruned away...
So, notes to myself:
- look more closely what goes wrong with this app
- think about a more appropriate android specific call graph pruning policy
