### ISSUE TITLE
StackOverflowError in GraphWalker.dfs

### ISSUE THREAD

**Issue by bnord01** [mohrm/android-analyzer#2]
Running quickscan with call graph construction on org.projectmaxs.module.clipboard_28.apk from fdroid yields the following error:

```
Exception in thread "main" java.lang.StackOverflowError
        at java.util.HashMap.putVal(HashMap.java:630)
        at java.util.HashMap.put(HashMap.java:611)
        at java.util.HashSet.add(HashSet.java:219)
        at edu.kit.joana.wala.core.graphs.GraphWalker.dfs(GraphWalker.java:53)
        at edu.kit.joana.wala.core.graphs.GraphWalker.dfs(GraphWalker.java:63)
        at edu.kit.joana.wala.core.graphs.GraphWalker.dfs(GraphWalker.java:63)
        at edu.kit.joana.wala.core.graphs.GraphWalker.dfs(GraphWalker.java:63)
        at edu.kit.joana.wala.core.graphs.GraphWalker.dfs(GraphWalker.java:63)
        at edu.kit.joana.wala.core.graphs.GraphWalker.dfs(GraphWalker.java:63)
        at edu.kit.joana.wala.core.graphs.GraphWalker.dfs(GraphWalker.java:63)
        at edu.kit.joana.wala.core.graphs.GraphWalker.dfs(GraphWalker.java:63)
        at edu.kit.joana.wala.core.graphs.GraphWalker.dfs(GraphWalker.java:63)
        at edu.kit.joana.wala.core.graphs.GraphWalker.dfs(GraphWalker.java:63)
```

**Comment by mohrm** [comment]
I cannot reproduce this anymore. Are you sure that you ran the QuickScanner? Usually, GraphWalker.dfs is called during PDG construction and should not be called if only the call graph shall be constructed. It might be the case that the PDG was built also in the QuickScanner setting (see https://github.com/mohrm/android-analyzer/commit/4d63c6cdfd4e627a2e5e996fc7b21c47a4ce84fe), so in this sense, this bug should not be there anymore.

**Comment by mohrm** [comment]
btw, I can also not reproduce this behaviour when running ShortAnalysis (so when a PDG is constructed). Is your stack size too small?

**Comment by bnord01** [comment]
I originally ran this using the quickscan bash script (at 901000b6c1f284a822aeebbcabf91be1ebf22a51 ).
I still get the same error after updating to 56a05779ebf932c5711e4005ba80680761d02860 (joana version jgf/joana@01382c70c93ba5bffdb26db91b0f57c1f15429f3 )

I'm using java: 
$ java -version
java version "1.8.0_51"
Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.51-b03, mixed mode)

I get this both on my mac book using osx and on a ubuntu linux server.

**Comment by bnord01** [comment]
Sorry, forgot to :ant:.
