### ISSUE TITLE
IllegalArgumentException (method is null) in DexEntryPoint

### ISSUE THREAD

**Issue by bnord01** [mohrm/android-analyzer#4]
Running quickcheck (without call graph constrution) on 

org.ardour_1.apk 
com.volosyukivan_30.apk
com.hexad.bluezime_17.apk
se.sandos.android.delayed_18.apk
net.haltcondition.anode_7.apk
com.example.sshtry_1.apk
com.qubling.sidekick_16.apk
ro.ieval.fonbot_2.apk

from fdroid yields the following error:

```
Exception in thread "main" java.lang.IllegalArgumentException: method is null
        at com.ibm.wala.ipa.callgraph.Entrypoint.<init>(Entrypoint.java:46)
        at com.ibm.wala.ipa.callgraph.impl.DefaultEntrypoint.<init>(DefaultEntrypoint.java:32)
        at com.ibm.wala.dalvik.ipa.callgraph.impl.DexEntryPoint.<init>(DexEntryPoint.java:64)
        at com.ibm.wala.dalvik.ipa.callgraph.impl.AndroidEntryPoint.<init>(AndroidEntryPoint.java:89)
        at edu.kit.jodroid.AndroidAnalysis.populateEntryPoints(Unknown Source)
        at edu.kit.jodroid.AndroidAnalysis.makeSDGBuilderConfig(Unknown Source)
        at edu.kit.jodroid.AndroidAnalysis.justScanFast(Unknown Source)
        at edu.kit.jodroid.QuickScanner.main(Unknown Source)
```

**Comment by mohrm** [comment]
fixed in eb8585e276dbaaf1bcf3b354a6b4e55faac15059
