### ISSUE TITLE
IllegalStateException in AndroidManifestXMLReader$IntentItem

### ISSUE THREAD

**Issue by bnord01** [mohrm/android-analyzer#6]
Running quickcheck (without call graph construction) on 

com.googamaphone.typeandspeak_36.apk
com.teamdc.stephendiniz.autoaway_23.apk
net.logomancy.dashquotes.civ5_1.apk
groomiac.crocodilenote_15.apk
ch.fixme.status_17.apk
com.github.marmalade.aRevelation_1.apk
com.github.grimpy.botifier_16.apk
apps.babycaretimer_6.apk (Also "Requested non existing handler for: ALIAS")
com.martinborjesson.o2xtouchlednotifications_81.apk

from fdroid yields the following error:

```
java.lang.IllegalStateException: Error in parser implementation! The required attribute 'name' which should have been defined in ACTION could not be retrieved. This should have been thrown before as it is a required attribute for ACTION
        at com.ibm.wala.dalvik.util.AndroidManifestXMLReader$IntentItem.leave(AndroidManifestXMLReader.java:594)
        at com.ibm.wala.dalvik.util.AndroidManifestXMLReader$SAXHandler.endElement(AndroidManifestXMLReader.java:686)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:609)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1782)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2973)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:649)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:333)
        at com.ibm.wala.dalvik.util.AndroidManifestXMLReader.readXML(AndroidManifestXMLReader.java:129)
        at com.ibm.wala.dalvik.util.AndroidManifestXMLReader.<init>(AndroidManifestXMLReader.java:105)
        at edu.kit.jodroid.AndroidAnalysis.makeSDGBuilderConfig(Unknown Source)
        at edu.kit.jodroid.AndroidAnalysis.justScanFast(Unknown Source)
        at edu.kit.jodroid.QuickScanner.main(Unknown Source)
Exception in thread "main" java.lang.IllegalStateException: Exception was thrown
        at com.ibm.wala.dalvik.util.AndroidManifestXMLReader.<init>(AndroidManifestXMLReader.java:108)
        at edu.kit.jodroid.AndroidAnalysis.makeSDGBuilderConfig(Unknown Source)
        at edu.kit.jodroid.AndroidAnalysis.justScanFast(Unknown Source)
        at edu.kit.jodroid.QuickScanner.main(Unknown Source)
```

**Comment by mohrm** [comment]
Running quickcheck (without call graph construction) on apps.babycaretimer_6.apk still yields the following, which appears to be very similar to #9.

Requested non existing handler for: ALIAS
Requested non existing handler for: ALIAS
java.lang.IllegalStateException: INTENT is not allowed as sub-tag of APPLICATION in Context:
    [ROOT, MANIFEST, APPLICATION, ACTIVITY, ALIAS]
    at com.ibm.wala.dalvik.util.AndroidManifestXMLReader$ParserItem.leave(AndroidManifestXMLReader.java:473)
    at com.ibm.wala.dalvik.util.AndroidManifestXMLReader$SAXHandler.endElement(AndroidManifestXMLReader.java:697)
    at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:609)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1783)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2970)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
    at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
    at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
    at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:642)
    at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:326)
    at com.ibm.wala.dalvik.util.AndroidManifestXMLReader.readXML(AndroidManifestXMLReader.java:129)
    at com.ibm.wala.dalvik.util.AndroidManifestXMLReader.<init>(AndroidManifestXMLReader.java:105)
    at edu.kit.jodroid.AndroidAnalysis.makeSDGBuilderConfig(AndroidAnalysis.java:143)
    at edu.kit.jodroid.AndroidAnalysis.justScanFast(AndroidAnalysis.java:218)
    at edu.kit.jodroid.QuickScanner.main(QuickScanner.java:84)
Exception in thread "main" java.lang.IllegalStateException: Exception was thrown
    at com.ibm.wala.dalvik.util.AndroidManifestXMLReader.<init>(AndroidManifestXMLReader.java:108)
    at edu.kit.jodroid.AndroidAnalysis.makeSDGBuilderConfig(AndroidAnalysis.java:143)
    at edu.kit.jodroid.AndroidAnalysis.justScanFast(AndroidAnalysis.java:218)
    at edu.kit.jodroid.QuickScanner.main(QuickScanner.java:84)

**Comment by mohrm** [comment]
I'll just add apps.babycaretimer_6.apk to #9 and close this issue.
