### ISSUE TITLE
IllegalStateException in AndroidManifestXMLReader$ParserItem

### ISSUE THREAD

**Issue by bnord01** [mohrm/android-analyzer#9]
Running quickcheck (without call graph construction) on 

ca.rmen.android.frenchcalendar_161.apk
com.androidemu.nes_61.apk
de.yazo_games.mensaguthaben_13.apk
com.androidemu.gbc_32.apk
com.java.SmokeReducer_1.apk (RECEIVER sub-tag of MANIFEST)
ru.qrck.quitetaskmanager_2.apk (RECEIVER sub-tag of MANIFEST)
apps.babycaretimer_6.apk

from fdroid yields the following error:

```
Requested non existing handler for: ALIAS
Requested non existing handler for: ALIAS
java.lang.IllegalStateException: INTENT is not allowed as sub-tag of APPLICATION in Context:
        [ROOT, MANIFEST, APPLICATION, ACTIVITY, ALIAS, INTENT]
        at com.ibm.wala.dalvik.util.AndroidManifestXMLReader$ParserItem.leave(AndroidManifestXMLReader.java:473)
        at com.ibm.wala.dalvik.util.AndroidManifestXMLReader$SAXHandler.endElement(AndroidManifestXMLReader.java:686)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:609)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1782)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2973)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:649)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:333)
        at com.ibm.wala.dalvik.util.AndroidManifestXMLReader.readXML(AndroidManifestXMLReader.java:129)
        at com.ibm.wala.dalvik.util.AndroidManifestXMLReader.<init>(AndroidManifestXMLReader.java:105)
        at edu.kit.jodroid.AndroidAnalysis.makeSDGBuilderConfig(Unknown Source)
        at edu.kit.jodroid.AndroidAnalysis.justScanFast(Unknown Source)
        at edu.kit.jodroid.QuickScanner.main(Unknown Source)
Exception in thread "main" java.lang.IllegalStateException: Exception was thrown
        at com.ibm.wala.dalvik.util.AndroidManifestXMLReader.<init>(AndroidManifestXMLReader.java:108)
        at edu.kit.jodroid.AndroidAnalysis.makeSDGBuilderConfig(Unknown Source)
        at edu.kit.jodroid.AndroidAnalysis.justScanFast(Unknown Source)
        at edu.kit.jodroid.QuickScanner.main(Unknown Source)
```

**Comment by mohrm** [comment]
Most of these errors are caused by [Activity Aliases](http://developer.android.com/guide/topics/manifest/activity-alias-element.html) which are not supported yet by the manifest processing.
an alias is just another name for an activity, so if the implementation is sensible, this should not be hard to implement...

**Comment by mohrm** [comment]
Also observed on apps.babycaretimer_6.apk; see https://github.com/mohrm/android-analyzer/issues/6#issuecomment-160137119

**Comment by bnord01** [comment]
Was already in the list.

**Comment by mohrm** [comment]
running the above described setup on
com.java.SmokeReducer_1.apk (RECEIVER sub-tag of MANIFEST)
ru.qrck.quitetaskmanager_2.apk (RECEIVER sub-tag of MANIFEST)
still yields something like

java.lang.IllegalStateException: RECEIVER is not allowed as sub-tag of MANIFEST in Context:
    [ROOT, MANIFEST, APPLICATION, ACTIVITY, SERVICE]
    at com.ibm.wala.dalvik.util.AndroidManifestXMLReader$ParserItem.leave(AndroidManifestXMLReader.java:473)
    at com.ibm.wala.dalvik.util.AndroidManifestXMLReader$SAXHandler.endElement(AndroidManifestXMLReader.java:703)
    at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:609)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1783)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2970)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
    at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
    at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
    at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:642)
    at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:326)
    at com.ibm.wala.dalvik.util.AndroidManifestXMLReader.readXML(AndroidManifestXMLReader.java:129)
    at com.ibm.wala.dalvik.util.AndroidManifestXMLReader.<init>(AndroidManifestXMLReader.java:105)
    at edu.kit.jodroid.AndroidAnalysis.makeSDGBuilderConfig(AndroidAnalysis.java:143)
    at edu.kit.jodroid.AndroidAnalysis.justScanFast(AndroidAnalysis.java:218)
    at edu.kit.jodroid.QuickScanner.main(QuickScanner.java:84)
Exception in thread "main" java.lang.IllegalStateException: Exception was thrown
    at com.ibm.wala.dalvik.util.AndroidManifestXMLReader.<init>(AndroidManifestXMLReader.java:108)
    at edu.kit.jodroid.AndroidAnalysis.makeSDGBuilderConfig(AndroidAnalysis.java:143)
    at edu.kit.jodroid.AndroidAnalysis.justScanFast(AndroidAnalysis.java:218)
    at edu.kit.jodroid.QuickScanner.main(QuickScanner.java:84)

**Comment by mohrm** [comment]
The manifest of com.java.SmokeReducer_1.apk looks like this:

```
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.java.SmokeReducer">
    <application android:icon="@drawable/icon" android:label="@string/app_name">
        <activity android:label="@string/app_name" android:launchMode="singleInstance" android:name="SmokeReducer">
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        <service android:name="ForegroundService"/>
        <receiver android:name="AlarmReceiver"/>
        <application android:icon="@drawable/icon" android:label="@string/app_name" android:launchMode="singleInstance" android:name="MyGlobals"/>
        <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    </application>
</manifest>
```

In particular, two applications are declared, one nested within the other.

According to the [documentation](http://developer.android.com/guide/topics/manifest/manifest-intro.html#filec), this is not allowed at all so the parser is right to crash (albeit for the wrong reasons).
As workarounds, I suggest:
- ignore the inner application(s) (this may be what really happens in Android)
- validate the manifest before feeding it to JoDroid (complete validation seems to be impossible; maybe just check that there is exactly one `<application>` and exactly one `<manifest>` tag).

**Comment by mohrm** [comment]
The manifest of ru.qrck.quitetaskmanager_2.apk looks like this:

```
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="ru.qrck.quitetaskmanager">
    <uses-permission android:name="android.permission.KILL_BACKGROUND_PROCESSES"/>
    <uses-permission android:name="android.permission.RESTART_PACKAGES"/>
    <uses-permission android:name="android.permission.GET_TASKS"/>
    <uses-permission android:name="android.permission.GET_PACKAGE_SIZE"/>
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
    <application android:icon="@drawable/icon" android:label="@string/app_name">
        <activity android:label="@string/app_name" android:launchMode="singleTop" android:name=".TaskManager">
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        <service android:name=".ForegroundService">
            <intent-filter>
                <action android:name="ru.qrck.quitetaskmanager.FOREGROUND"/>
            </intent-filter>
        </service>
        <activity android:label="Preferences" android:name=".PrefsPage"/>
    </application>
    <receiver android:name="StartupIntentReceiver">
        <intent-filter>
            <action android:name="android.intent.action.BOOT_COMPLETED"/>
            <category android:name="android.intent.category.HOME"/>
        </intent-filter>
    </receiver>
</manifest>
```

Here the problem is that a `<receiver>` tag is nested directly in a `<manifest>` tag - so the error message is [right](http://developer.android.com/guide/topics/manifest/manifest-element.html) :+1: 
So this app does not have a valid manifest and therefore it is not really a bug that the manifest parser crashes here. A similar workaround as [above](https://github.com/mohrm/android-analyzer/issues/9#issuecomment-161034483) should fix this problem.
